### ISSUE TITLE
RabbitMQ consumer shutdown - Transport connection is unhealthy, reconnection

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#1089]
Running DotNetCore.Cap 6.01, RabbitMQ (Standalone running on windows 2019 server), SQL Server 2019, C# program (dotnet core 6.0.102).

Sometime over the weekend, I started seeing the messages in the log:
RabbitMQ consumer shutdown. --> Goodbye
RabbitMQ consumer cancelled. --> amq.ctag-vMGWgLTtVoDRcewhrQLkyQ
Transport connection is unhealthy, reconnection...

I see the first 2 usually once a day from some different systems (Same RabbitMQ server), but this weekend's messages add the Transport connection is unhealthy, reconnection. It didn't seem like it was actually reconnecting. I wasn't sure if I needed some additional code to trigger that reconnection or not. I would have to find out how to trouble this issue and stop it, but if there is a way to detect the connection is  unhealthy, I'd like to shut the program down restart it. The RabbitMQ is running on the same Machine as the software so its strange its loosing connection.

The configuration is fairly simple:
services.AddCap(x =>
            {
                x.UseEntityFramework<L2ExternalContext>();
                x.UseRabbitMQ(opt =>
                {
                    opt.ConnectionFactoryOptions = f =>
                    {
                        f.HostName = "xxxxxxxxx;
                        f.Password = "xxxx";
                        f.UserName = "xxx";
                    };
                });
                x.FailedRetryCount = 10;
                x.FailedThresholdCallback = failed =>
                {
                    var logger = failed.ServiceProvider.GetService<ILogger<Program>>();
                    logger.LogError("A message of type {MessageType} failed after executing {FailedRetryCount} several times, requiring manual troubleshooting. " +
                        "Message name: {GetName}",failed.MessageType,x.FailedRetryCount,failed.Message.GetName());
                };

                //x.SucceedMessageExpiredAfter = 14400;// 60 * 60;//one hour
                x.CollectorCleaningInterval = 24 * 3600;//24 hours //60 * 60;//one hour
            });

Any ideas or things I should try?

**Comment by yang-xiaodong** [comment]
The reconnection is automatic, it looks like the client closed the connection. Are there any steps to reproduce this issue?

**Comment by KayakFisher205** [comment]
At the moment, no. I just restarted my program without doing anything to the RabbitMQ and it has been working fine since yesterday. 

I have a RichTextBox capturing the Serilog (Serilog.Sinks.RichTextBox.Wpf) output like below. If I want to catch the 'Transport connection unhealthy' debug message, is there an easy way in CAP? I would like to either email or maybe shutdown and restart the software to get back on track.

Since CAP created the Exchange (cap.default.router Durable and Direct) and the Queue (based on the program name, classic, durable, x-message-ttl: 864000000), are there any features I should add in RabbitMQ?
Attached a screenshot of the Exchange to show there isn't a ton of traffic so I don't think its overloaded. Just strange since the c# program and RabbitMQ (via ERL) are running on the same server.




[2022-02-22 08:38:28.922 -06:00 DotNetCore.CAP.Processor.TransportCheckProcessor DBG] Transport connection healthy!
[2022-02-22 08:38:58.951 -06:00 DotNetCore.CAP.Processor.TransportCheckProcessor DBG] Transport connection checking...
[2022-02-22 08:38:58.951 -06:00 DotNetCore.CAP.Processor.TransportCheckProcessor DBG] Transport connection healthy
![Screenshot 2022-02-22 084837](https://user-images.githubusercontent.com/71768711/155157038-be21f625-70de-4103-8919-284dd58f3fcb.png)
!

**Comment by yang-xiaodong** [comment]
You can add a custom a TransportCheckProcessor and then add some custom logic to capture the log.

Example: 
```C#
public class MyTransportCheckProcessor : IProcessor
{
    private readonly ILogger<TransportCheckProcessor> _logger;
    private readonly IConsumerRegister _register;
    private readonly TimeSpan _waitingInterval;

    public TransportCheckProcessor(ILogger<TransportCheckProcessor> logger, IConsumerRegister register)
    {
        _logger = logger;
        _register = register;
        _waitingInterval = TimeSpan.FromSeconds(30);
    }

    public async Task ProcessAsync(ProcessingContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ThrowIfStopping();

        _logger.LogDebug("Transport connection checking...");

        if (!_register.IsHealthy())
        {
            _logger.LogWarning("Transport connection is unhealthy, reconnection...");

           //**************************************** Here add your logic   ******************************

            _register.ReStart();
        }
        else
        {
            _logger.LogDebug("Transport connection healthy!");
        }

        await context.WaitAsync(_waitingInterval);
    }
}
```

Replace the default implement.

```C#
services.AddSingleton<MyTransportCheckProcessor>();
services.AddCap(x => {});
```

**Comment by KayakFisher205** [comment]
I've not had a chance to test this. I will next week. Thanks for the help.

**Comment by KayakFisher205** [comment]
I tried the code above, but I did have to change the Constructor to MyTransportCheckProcessor. I went ahead and changed the ILogger too (wasn't 100% sure about that one).

I implemented it before the AddCap but it didn't seem to be overriding.

I changed the Debug messages to "Custom Transport connection checking..." and "Custom Transport connection is unhealthy, reconnection...", but it continued to show the standard messages. Also, in the debug message it shows
2022-02-28 04:07:32.324 -06:00 DotNetCore.CAP.Processor.TransportCheckProcessor DBG] 
and I'm not sure it its supposed to be MyTransportCheckProcessor or not. Maybe I didn't set it up correctly.
[TransportCheckProcessor.zip](https://github.com/dotnetcore/CAP/files/8153606/TransportCheckProcessor.zip)
I've attached the class to check.
![image](https://user-images.githubusercontent.com/71768711/155990981-8c7b3fb3-2516-478b-a145-121217971f97.png)

**Comment by Allen-dududu** [comment]
> 

I don't think that can work. CAP only get the processors that type are TransportCheckProcessor,MessageNeedToRetryProcessor,CollectorProcessor. ![image](https://user-images.githubusercontent.com/38786932/156119358-2724c987-7b92-4e46-868f-e90449fa5b50.png)
Even you change the name of MyTransportCheckProcessor to TransportCheckProcessor, it still does not work.

**Comment by yang-xiaodong** [comment]
@Allen-dududu is right, I miss it.

I have tweak the ProcessAsync to virtual for override in preview version ` 6.1.0-preview-162971117`.

```cs
public class MyTransportCheckProcessor : TransportCheckProcessor
{
    private readonly ILogger<TransportCheckProcessor> _logger;
    private readonly IConsumerRegister _register;
    private readonly TimeSpan _waitingInterval;

    public MyTransportCheckProcessor(ILogger<TransportCheckProcessor> logger, IConsumerRegister register)
        :base(logger, register)
    {
        _logger = logger;
        _register = register;
        _waitingInterval = TimeSpan.FromSeconds(30);
    }

    public override async Task ProcessAsync(ProcessingContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.ThrowIfStopping();

        _logger.LogDebug("Transport connection checking...");

        if (!_register.IsHealthy())
        {
            _logger.LogWarning("Transport connection is unhealthy, reconnection...");

           //**************************************** Here add your logic   ******************************

            _register.ReStart();
        }
        else
        {
            _logger.LogDebug("Transport connection healthy!");
        }

        await context.WaitAsync(_waitingInterval);
    }
}

```

Replace the default implement.

```cs
services.AddSingleton<MyTransportCheckProcessor>();
services.AddSingleton<TransportCheckProcessor>(x=>x.GetRequiredService<MyTransportCheckProcessor>());
services.AddCap(x => {});
```

**Comment by KayakFisher205** [comment]
Thanks. I was able to implement this code. Lets close this issue and I will create another if/once I found out what causing the error, if it was related to CAP.

Thanks again for the help
